#!/usr/bin/env bash

set -euo pipefail
shopt -s globstar
IFS=$'\n\t'

echo test files can be run on its own
for FILE in test/isolated/*Test.ts; do
  node --loader ts-node/esm $FILE
done

rm -rf ./test/results
mkdir -p ./test/results

echo 'test files can be run using `ars` cli'
./bin/ars --loader ts-node/esm test/*Test.ts

./bin/ars test/cli/**/*Test.js
tests_run="$(ls test/results | wc -l)"
if [ $tests_run -ne 3 ]; then
  echo 'Fail!'
  exit 1
fi

rm -rf ./test/results
mkdir -p ./test/results

echo --only option
./bin/ars --only='also works' test/cli/**/*Test.js
tests_run="$(ls test/results | wc -l)"
if [ $tests_run -ne 1 ]; then
  echo 'Fail!'
  exit 1
fi

rm -rf ./test/results
mkdir -p ./test/results

echo line number
./bin/ars test/cli/one/otherTest.js:9
tests_run="$(ls test/results | wc -l)"
if [ $tests_run -ne 1 ]; then
  echo 'Fail!'
  exit 1
fi

rm -rf ./test/results
mkdir -p ./test/results

echo it expands globstar in node
# also adding random node flag
./bin/ars --no-deprecation 'test/cli/**/*Test.js'
tests_run="$(ls test/results | wc -l)"
if [ $tests_run -ne 3 ]; then
  echo 'Fail!'
  exit 1
fi

echo it exits 1 on failure
set +e
./bin/ars test/error/failTest.js
if [ $? -ne 1 ]; then
  echo 'Fail!'
  exit 1
fi
