#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

js_file_regex=".js$"
cmd='node '

for arg in "$@"; do
  if [[ $arg =~ $js_file_regex ]]; then
    cmd="$cmd -r ./$arg "
  else
    cmd="$cmd $arg "
  fi
done

eval "$cmd ./run.js"
